name: Developer_Branch_CI
on: [push]

jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: i am running shell script
        shell: bash
        run: bash script.sh
